image: clever/drone-go:1.5
publish:
  docker:
  docker_host: $$docker_server
  email: $$docker_email
  image_name: clever/docker-demo
  password: $$docker_password
  registry_login: true
  tags:
    - $(git rev-parse --short HEAD)
  username: $$docker_username
  when:
    branch: master
script:
  - make
